DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nickname VARCHAR(255) NULL,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       birthday DATE NULL,
                       sex VARCHAR(10) NULL,
                       about TEXT NULL,
                       is_seller BOOLEAN NULL,
                       surname VARCHAR(255) NULL,
                       name VARCHAR(255)  NULL,
                       patronymic VARCHAR(255)  NULL,
                       is_confirmed BOOLEAN  NULL,
                       confirm_token VARCHAR(255) NULL,
                       language VARCHAR(255) NULL,
                       is_mailling BOOLEAN NULL,
                       password VARCHAR(255)  NULL
);
